env: "local"
http_server:
  address: ":8082"
  timeout: 600s
  idle_timeout: 30s
  context_timeout: 10s
runner:
  compile_timeout: 20
  run_timeout: 6
  run_cpu_timeout: 3
  compile_cpu_timeout: 10
  compile_memory_limit_KB: 51200
  run_memory_limit_KB: 51200